### ISSUE TITLE
Provide option to run Islandora Bagger on local filesystem, without interacting with its REST API

### ISSUE THREAD

**Issue by mjordan** [mjordan/islandora_bagger_integration#12]
Even though the architecture of this module is intended to offload the heavy lifting of creating a Bag to a distributed microservice, some sites might prefer simplicity over scalability. We could add an option to this module to call Bagger's `app:islandora_bagger:create_bag` command directly, and present the user with a download link for their Bag.

**Comment by mjordan** [comment]
The issue-12 branch adds a new block ("Bagit block (local)") that calls Islandora Bagger on Drupal's local filesystem. In this configuration, submitting the "Create Bag" button doesn't send a request to Islandora Bagger's REST interface and add the request to a queue that is processed later, it calls Islandora Bagger as a console command in realtime and presents a download link to the user.

To use this option, visit the module's settings form and add the absolute path to where your local Islandora Bagger is installed.

Currently, the download link assumes that the Bag is written to Drupal's public filesystem. This means that the `output_dir` option in the YAML config file used must be the absolute path to your Drupal's public filesystem, e.g. `output_dir: /var/www/html/drupal/web/sites/default/files`.

**Comment by mjordan** [comment]
Two things we'll need to consider: the Bag sits around after it's been downloaded, so site admins will want a way to clean them up, and since the Bag is written to the public filesystem, anyone can access any Bag, which is a major security flaw.

**Comment by ajstanley** [comment]
This is some nice work, Mark.  I'll test it on my VM.

**Comment by mjordan** [comment]
Cool. [This](https://www.drupal.org/project/drupal/issues/233997) would have been useful to clean up downloaded files, but it appears that it will never make it into D8 (see comment 21).

**Comment by mjordan** [comment]
BTW, the path to the YAML config file is still hard coded at https://github.com/mjordan/islandora_bagger_integration/blob/issue-12/src/Plugin/Form/IslandoraBaggerLocalForm.php#L92. When use the variable, Drupal reports the file is not found.

**Comment by mjordan** [comment]
Issue with the path to the YAML config file as described in the previous comment is resolved.

**Comment by mjordan** [comment]
The admin settings form should provide a toggle to indicate whether the module is using a remote microservice or a local version of Bagger. This way, we can hide the admin setting(s) that do not pertain.

**Comment by mjordan** [comment]
Merged.
