### ISSUE TITLE
Bagger block not showing

### ISSUE THREAD

**Issue by johnguirgis** [mjordan/islandora_bagger_integration#27]
I am trying to use the Islandora Bagger Integration module on Drupal 9 but the block that allows users to create bags is not showing up on any page regardless of where I place it in block layout. 
I cloned the islandora_bagger_integration module, enabled it from Drupal and placed the Islandora Bagger Block in block layout but no matter where I place, it is now showing up on any of the pages. 
Any idea on why this might be or how to resolve it?

**Comment by mjordan** [comment]
@johnguirgis I can't replicate that behavior. I'm using the Olivera theme, Drupal 9.3.0-dev. When I add the block and restrict to content type "Repository Item", it appears as expected:

![image](https://user-images.githubusercontent.com/403918/129911077-a14fd3b2-ca78-4521-a943-ebc7d3ef473a.png)

In this case, I added the block to the "Content Below" block but it works for any any block region I choose and am viewing the nodes as the admin user.

To confirm, do other blocks work as intended?

**Comment by johnguirgis** [comment]
@mjordan Thanks for your response. There was an issue with another module on the page that was preventing the block from showing up but I have resolved it.
